### ISSUE TITLE
Incorrect assignment in NewAKOSettings

### ISSUE THREAD

**Issue by HanFa** [vmware-samples/load-balancer-operator-for-kubernetes#17]
https://github.com/vmware-samples/load-balancer-operator-for-kubernetes/blob/0b16d578dd4aee3e4973624eb92729b6e2b7707a/pkg/ako/values.go#L206

/kind bug

**Comment by XudongLiuHarold** [comment]
Great catch @HanFa , could you submit a fix for this? 

/assign @HanFa

**Comment by HanFa** [comment]
Sure will do!
